### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by S1SYPHOS** [michnhokn/kirby3-logger#1]
Hey there,
I just installed your plugin and I'm pleased so far - but one thing I wanted to give feedback about: In the project's README, you state that "permissions" are to be included in the future - do you mean like this:

```yaml
# site/blueprints/users/role.yml
permissions:
  access:
    kirby3-logger: false
```

... which works as of right now :fox_face:
